// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: indicators/metric/metric_model.proto

package indicators

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type MetricAggregate struct {
	Instance             string    `protobuf:"bytes,1,opt,name=Instance,proto3" json:"Instance,omitempty"`
	Namespace            string    `protobuf:"bytes,2,opt,name=Namespace,proto3" json:"Namespace,omitempty"`
	Timestamp            int64     `protobuf:"varint,3,opt,name=Timestamp,proto3" json:"Timestamp,omitempty"`
	Metrics              []*Metric `protobuf:"bytes,4,rep,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MetricAggregate) Reset()         { *m = MetricAggregate{} }
func (m *MetricAggregate) String() string { return proto.CompactTextString(m) }
func (*MetricAggregate) ProtoMessage()    {}
func (*MetricAggregate) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94905ea1eaa7294, []int{0}
}
func (m *MetricAggregate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricAggregate.Unmarshal(m, b)
}
func (m *MetricAggregate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricAggregate.Marshal(b, m, deterministic)
}
func (m *MetricAggregate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricAggregate.Merge(m, src)
}
func (m *MetricAggregate) XXX_Size() int {
	return xxx_messageInfo_MetricAggregate.Size(m)
}
func (m *MetricAggregate) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricAggregate.DiscardUnknown(m)
}

var xxx_messageInfo_MetricAggregate proto.InternalMessageInfo

func (m *MetricAggregate) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

func (m *MetricAggregate) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *MetricAggregate) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MetricAggregate) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type Metric struct {
	Metric               string            `protobuf:"bytes,1,opt,name=Metric,proto3" json:"Metric,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,2,rep,name=Tags,proto3" json:"Tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Value                float64           `protobuf:"fixed64,3,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_f94905ea1eaa7294, []int{1}
}
func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (m *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(m, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *Metric) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Metric) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*MetricAggregate)(nil), "indicators.MetricAggregate")
	proto.RegisterType((*Metric)(nil), "indicators.Metric")
	proto.RegisterMapType((map[string]string)(nil), "indicators.Metric.TagsEntry")
}

func init() {
	proto.RegisterFile("indicators/metric/metric_model.proto", fileDescriptor_f94905ea1eaa7294)
}

var fileDescriptor_f94905ea1eaa7294 = []byte{
	// 252 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0xc9, 0xcc, 0x4b, 0xc9,
	0x4c, 0x4e, 0x2c, 0xc9, 0x2f, 0x2a, 0xd6, 0xcf, 0x4d, 0x2d, 0x29, 0xca, 0x4c, 0x86, 0x52, 0xf1,
	0xb9, 0xf9, 0x29, 0xa9, 0x39, 0x7a, 0x05, 0x45, 0xf9, 0x25, 0xf9, 0x42, 0x5c, 0x08, 0x55, 0x4a,
	0xd3, 0x19, 0xb9, 0xf8, 0x7d, 0xc1, 0x4a, 0x1c, 0xd3, 0xd3, 0x8b, 0x52, 0xd3, 0x13, 0x4b, 0x52,
	0x85, 0xa4, 0xb8, 0x38, 0x3c, 0xf3, 0x8a, 0x4b, 0x12, 0xf3, 0x92, 0x53, 0x25, 0x18, 0x15, 0x18,
	0x35, 0x38, 0x83, 0xe0, 0x7c, 0x21, 0x19, 0x2e, 0x4e, 0xbf, 0xc4, 0xdc, 0xd4, 0xe2, 0x82, 0xc4,
	0xe4, 0x54, 0x09, 0x26, 0xb0, 0x24, 0x42, 0x00, 0x24, 0x1b, 0x92, 0x99, 0x9b, 0x5a, 0x5c, 0x92,
	0x98, 0x5b, 0x20, 0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x1c, 0x84, 0x10, 0x10, 0xd2, 0xe1, 0x62, 0x87,
	0xb8, 0xa6, 0x58, 0x82, 0x45, 0x81, 0x59, 0x83, 0xdb, 0x48, 0x48, 0x0f, 0xe1, 0x12, 0x3d, 0x88,
	0x2b, 0x82, 0x60, 0x4a, 0x94, 0x16, 0x32, 0x72, 0xb1, 0x41, 0xc4, 0x84, 0xc4, 0x60, 0x2c, 0xa8,
	0x73, 0x60, 0xe2, 0x06, 0x5c, 0x2c, 0x21, 0x89, 0xe9, 0xc5, 0x12, 0x4c, 0x60, 0xd3, 0x64, 0x30,
	0x4d, 0xd3, 0x03, 0x49, 0xbb, 0xe6, 0x95, 0x14, 0x55, 0x06, 0x81, 0x55, 0x0a, 0x89, 0x70, 0xb1,
	0x86, 0x25, 0xe6, 0x94, 0xa6, 0x82, 0x1d, 0xc7, 0x18, 0x04, 0xe1, 0x48, 0x99, 0x73, 0x71, 0xc2,
	0x15, 0x0a, 0x09, 0x70, 0x31, 0x67, 0xa7, 0x56, 0x42, 0x6d, 0x02, 0x31, 0x41, 0x9a, 0xca, 0xc0,
	0x9a, 0x20, 0xfe, 0x85, 0x70, 0xac, 0x98, 0x2c, 0x18, 0x93, 0xd8, 0xc0, 0x01, 0x6a, 0x0c, 0x08,
	0x00, 0x00, 0xff, 0xff, 0x48, 0x7e, 0x99, 0x15, 0x78, 0x01, 0x00, 0x00,
}
