// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: indicators/metric_model.proto

package indicators

import (
	fmt "fmt"
	proto "github.com/gogo/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type MetricAggregate struct {
	Classify             string    `protobuf:"bytes,1,opt,name=classify,proto3" json:"classify,omitempty"`
	Instance             string    `protobuf:"bytes,2,opt,name=instance,proto3" json:"instance,omitempty"`
	Namespace            string    `protobuf:"bytes,3,opt,name=namespace,proto3" json:"namespace,omitempty"`
	Timestamp            int64     `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Metrics              []*Metric `protobuf:"bytes,5,rep,name=metrics,proto3" json:"metrics,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MetricAggregate) Reset()         { *m = MetricAggregate{} }
func (m *MetricAggregate) String() string { return proto.CompactTextString(m) }
func (*MetricAggregate) ProtoMessage()    {}
func (*MetricAggregate) Descriptor() ([]byte, []int) {
	return fileDescriptor_96e18b2d9d0e7c7d, []int{0}
}
func (m *MetricAggregate) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MetricAggregate.Unmarshal(m, b)
}
func (m *MetricAggregate) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MetricAggregate.Marshal(b, m, deterministic)
}
func (m *MetricAggregate) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MetricAggregate.Merge(m, src)
}
func (m *MetricAggregate) XXX_Size() int {
	return xxx_messageInfo_MetricAggregate.Size(m)
}
func (m *MetricAggregate) XXX_DiscardUnknown() {
	xxx_messageInfo_MetricAggregate.DiscardUnknown(m)
}

var xxx_messageInfo_MetricAggregate proto.InternalMessageInfo

func (m *MetricAggregate) GetClassify() string {
	if m != nil {
		return m.Classify
	}
	return ""
}

func (m *MetricAggregate) GetInstance() string {
	if m != nil {
		return m.Instance
	}
	return ""
}

func (m *MetricAggregate) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *MetricAggregate) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *MetricAggregate) GetMetrics() []*Metric {
	if m != nil {
		return m.Metrics
	}
	return nil
}

type Metric struct {
	Metric               string            `protobuf:"bytes,1,opt,name=Metric,proto3" json:"Metric,omitempty"`
	Tags                 map[string]string `protobuf:"bytes,2,rep,name=tags,proto3" json:"tags,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Value                float64           `protobuf:"fixed64,3,opt,name=Value,proto3" json:"Value,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Metric) Reset()         { *m = Metric{} }
func (m *Metric) String() string { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()    {}
func (*Metric) Descriptor() ([]byte, []int) {
	return fileDescriptor_96e18b2d9d0e7c7d, []int{1}
}
func (m *Metric) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Metric.Unmarshal(m, b)
}
func (m *Metric) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Metric.Marshal(b, m, deterministic)
}
func (m *Metric) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Metric.Merge(m, src)
}
func (m *Metric) XXX_Size() int {
	return xxx_messageInfo_Metric.Size(m)
}
func (m *Metric) XXX_DiscardUnknown() {
	xxx_messageInfo_Metric.DiscardUnknown(m)
}

var xxx_messageInfo_Metric proto.InternalMessageInfo

func (m *Metric) GetMetric() string {
	if m != nil {
		return m.Metric
	}
	return ""
}

func (m *Metric) GetTags() map[string]string {
	if m != nil {
		return m.Tags
	}
	return nil
}

func (m *Metric) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func init() {
	proto.RegisterType((*MetricAggregate)(nil), "indicators.MetricAggregate")
	proto.RegisterType((*Metric)(nil), "indicators.Metric")
	proto.RegisterMapType((map[string]string)(nil), "indicators.Metric.TagsEntry")
}

func init() { proto.RegisterFile("indicators/metric_model.proto", fileDescriptor_96e18b2d9d0e7c7d) }

var fileDescriptor_96e18b2d9d0e7c7d = []byte{
	// 258 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcd, 0x4a, 0xc4, 0x30,
	0x10, 0xc7, 0x49, 0xbb, 0xbb, 0xda, 0xf1, 0xa0, 0x04, 0x91, 0xb0, 0xac, 0x50, 0xf6, 0xd4, 0x83,
	0x54, 0xd1, 0x83, 0xe2, 0xcd, 0x83, 0x47, 0x2f, 0x41, 0xbc, 0xca, 0x98, 0x8d, 0x21, 0xd8, 0xa4,
	0x25, 0x89, 0xc2, 0x3e, 0x8e, 0xcf, 0xe0, 0x0b, 0x4a, 0x13, 0xd3, 0x1e, 0xbc, 0xcd, 0xff, 0x63,
	0x86, 0x1f, 0x03, 0xe7, 0xda, 0xee, 0xb4, 0xc0, 0xd0, 0x3b, 0x7f, 0x69, 0x64, 0x70, 0x5a, 0xbc,
	0x9a, 0x7e, 0x27, 0xbb, 0x76, 0x70, 0x7d, 0xe8, 0x29, 0xcc, 0xf1, 0xf6, 0x87, 0xc0, 0xf1, 0x53,
	0xac, 0x3c, 0x28, 0xe5, 0xa4, 0xc2, 0x20, 0xe9, 0x1a, 0x0e, 0x45, 0x87, 0xde, 0xeb, 0xf7, 0x3d,
	0x23, 0x35, 0x69, 0x2a, 0x3e, 0xe9, 0x31, 0xd3, 0xd6, 0x07, 0xb4, 0x42, 0xb2, 0x22, 0x65, 0x59,
	0xd3, 0x0d, 0x54, 0x16, 0x8d, 0xf4, 0x03, 0x0a, 0xc9, 0xca, 0x18, 0xce, 0xc6, 0x98, 0x06, 0x6d,
	0xa4, 0x0f, 0x68, 0x06, 0xb6, 0xa8, 0x49, 0x53, 0xf2, 0xd9, 0xa0, 0x17, 0x70, 0x90, 0x48, 0x3d,
	0x5b, 0xd6, 0x65, 0x73, 0x74, 0x4d, 0xdb, 0x99, 0xb2, 0x4d, 0x84, 0x3c, 0x57, 0xb6, 0xdf, 0x04,
	0x56, 0xc9, 0xa3, 0x67, 0x79, 0xfa, 0x43, 0xcd, 0xfe, 0x15, 0x2c, 0x02, 0x2a, 0xcf, 0x8a, 0x78,
	0x6d, 0xf3, 0xff, 0x5a, 0xfb, 0x8c, 0xca, 0x3f, 0xda, 0xe0, 0xf6, 0x3c, 0x36, 0xe9, 0x29, 0x2c,
	0x5f, 0xb0, 0xfb, 0x4c, 0xe8, 0x84, 0x27, 0xb1, 0xbe, 0x85, 0x6a, 0x2a, 0xd2, 0x13, 0x28, 0x3f,
	0x64, 0x7e, 0xca, 0x38, 0x8e, 0x4b, 0x5f, 0x71, 0x29, 0x3d, 0x23, 0x89, 0xfb, 0xe2, 0x8e, 0xbc,
	0xad, 0xe2, 0xb3, 0x6f, 0x7e, 0x03, 0x00, 0x00, 0xff, 0xff, 0xd1, 0x0c, 0x42, 0xbb, 0x8d, 0x01,
	0x00, 0x00,
}
